# Generated by Django 2.1.3 on 2019-11-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191104_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ManyToManyField(through='articles.Membership', to='articles.Article'),
        ),
    ]
